
/**
 * psIMU calibration header. Automatically generated by psIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

accel_bias[0] = -211;
accel_bias[1] = -37;
accel_bias[2] = -2;
accel_scale[0] = 3798.405401;
accel_scale[1] = 4355.937539;
accel_scale[2] = 4165.295610;

mag_bias[0] = 249;
mag_bias[1] = 22;
mag_bias[2] = 132;
mag_scale[0] = 459.630087;
mag_scale[1] = 475.958118;
mag_scale[2] = 461.666950;
